# Generated by Django 5.0.7 on 2024-07-24 20:30

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('state', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AM', 'Amazonas'), ('AP', 'Amapá'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MG', 'Minas Gerais'), ('MS', 'Mato Grosso do Sul'), ('MT', 'Mato Grosso'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('PR', 'Paraná'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('RS', 'Rio Grande do Sul'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('SP', 'São Paulo'), ('TO', 'Tocantins')], max_length=2, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'ordering': ['state', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Cultura Plantada',
                'verbose_name_plural': 'Culturas Plantadas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=50, verbose_name='Nome do produtor')),
                ('farm_name', models.CharField(max_length=50, verbose_name='Nome da fazenda')),
                ('person_type', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], max_length=2, verbose_name='Tipo da Pessoa')),
                ('document', models.CharField(max_length=18, verbose_name='Documento')),
                ('total_area', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Área total (ha)')),
                ('arable_area', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Área agricultável (ha)')),
                ('vegetation_area', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Área de vegetação (ha)')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='farmers', to='farmers.city', verbose_name='Cidade')),
                ('cultures', models.ManyToManyField(to='farmers.culture', verbose_name='Culturas Plantadas')),
            ],
            options={
                'verbose_name': 'Produtor Rural',
                'verbose_name_plural': 'Produtores Rurais',
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='farmer',
            constraint=models.CheckConstraint(check=models.Q(('total_area__gte', django.db.models.expressions.CombinedExpression(models.F('arable_area'), '+', models.F('vegetation_area')))), name='check_total_area'),
        ),
    ]
